### ISSUE TITLE
Юзай линтеры

### ISSUE THREAD

**Issue by 460s** [introvertautist/statistic_generator#9]
https://github.com/introvertautist/statistic_generator/blob/923669f24dba65827d9bc9dcf3ce9e10b36172cf/main.go#L121

`docker run -v ${PWD}:${PWD} -w ${PWD} -it golangci/golangci-lint bash`

`golangci-lint run -E golint -E dupl -E goconst -E maligned -E misspell -E prealloc`

common.go:23:5: `Warn` is unused (deadcode)
    Warn    = Colored("\033[1;33m%s\033[0m")
    ^
common.go:74:6: `RandomInt` is unused (deadcode)
func RandomInt(min, max int) int {
     ^
generate_v5.go:101:9: ineffectual assignment to `payload` (ineffassign)
        payload := []NetflowPayloadV5{}
        ^
generate_v5.go:125:42: `trafic` is a misspelling of `traffic` (misspell)
NetflowV5Generator - Generate netflow v5 trafic
                                         ^
generate_v5.go:67:9: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
        fmt.Printf(Debug(
        ^
generate_v5.go:80:9: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
        fmt.Printf(Error("\nWriting netflow header failed: %s\n", err))
        ^
generate_v5.go:86:13: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
            fmt.Printf(Error("\nWriting netflow record failed: %s\n", err))
            ^

**Comment by introvertautist** [comment]
Done
